name: docker-build
on: [push]
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: build only
        id: docker_build
        uses: docker/buid-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/py-test.latest
      - name: Image digest
        run: echo ${{steps.docker_build.outputs.digest }}
